### ISSUE TITLE
Update for Angular 7 ?

### ISSUE THREAD

**Issue by falget** [matheusdavidson/angular-cropperjs#39]
Any chance we could get the Angular peer dependencies upped to build with Angular 7+ without npm warnings?

**Comment by BluebambooSRL** [comment]
I don not have any error when I do "npm i", or when I deploy it... but when I want to load the webpage I have this error.

core.js:15724 ERROR Error: Uncaught (in promise): Error: Template parse errors:
Can't bind to 'cropperOptions' since it isn't a known property of 'angular-cropper'.
1. If 'angular-cropper' is an Angular component and it has 'cropperOptions' input, then verify that it is part of this module.
2. If 'angular-cropper' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message.
3. To allow any property add 'NO_ERRORS_SCHEMA' to the '@NgModule.schemas' of this component. ("e"></angular-cropper>-->
   Ionic CLI                     : 5.0.3 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.4.2
   @angular-devkit/build-angular : 0.13.9
   @angular-devkit/schematics    : 7.3.9
   @angular/cli                  : 7.3.9
   @ionic/angular-toolkit        : 1.5.1

**Comment by luiscmas** [comment]
Hi, do you have plans to update dependencies to Angular 8.

If you try to update 

If not, can we make a pull request to add support to Angular 8?

**Comment by uahic** [comment]
Similar issue here

ng update @angular/cli @angular/core

results in


                  Package "angular-cropperjs" has an incompatible peer dependency to "@angular/common" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.2.3").
                  Package "angular-cropperjs" has an incompatible peer dependency to "@angular/core" (requires "^6.0.0-rc.0 || ^6.0.0" (extended), would install "8.2.3").

**Comment by jagomf** [comment]
If you can assert that the only dependency causing a problem when trying to upgrade to Angular 8, then you can just force the upgrade:

`ng update @angular/cli @angular/core --force`

This workaround will work fine, since author of this package is not properly maintaining or paying attention to open issues.

**Comment by matheusdavidson** [comment]
updated to v14+
